### ISSUE TITLE
The plugin does not work with Customies

### ISSUE THREAD

**Issue by Ent0ty** [DavyCraft648/MCFurniture#11]
- If I put the plugin on it and Customies also then this error comes up: [17:58:11.753] [AsyncWorker#1 thread/CRITICAL]: InvalidArgumentException: "Block ID 10706 is already used by another block" (EXCEPTION) in "pmsrc/src/block/RuntimeBlockStateRegistry" at line 93

**Comment by Azvyl** [comment]
This is not MCFurniture's fault, this plugin has registered the block in the correct way. One of your plugins registers a block with a different ID in another thread.

I discussed this in internals-dev channel: https://discord.com/channels/373199722573201408/546255162222706696/1142020838107910164
