### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GabBiswajit** [DavyCraft648/MCFurniture#12]
`
pocketmine\block\RuntimeBlockStateRegistry->register(object DavyCraft648\MCFurniture\block\Basin#27110)`
Everytime When I Start.....
`
Thread: AsyncWorker#0
Error: Block ID 10710 is already used by another block
File: pmsrc/src/block/RuntimeBlockStateRegistry
Line: 93
Type: InvalidArgumentException
Backtrace:`
Can you register than with defrind I'd for everyone block ??

**Comment by GabBiswajit** [comment]
@DavyCraft648

**Comment by Azvyl** [comment]
https://github.com/DavyCraft648/MCFurniture/issues/11#issuecomment-1741975232
