### ISSUE TITLE
wall cabinet faces

### ISSUE THREAD

**Issue by ZhorifCraft451** [DavyCraft648/MCFurniture#6]
![Minecraft Screenshot 2023 06 24 - 11 02 59 66](https://github.com/DavyCraft648/MCFurniture/assets/75656616/0c29d889-4f07-4c50-b584-d4c5aa5791bc)

**Comment by Azvyl** [comment]
update customies kalo yang kamu maksud itu rotationnya

**Comment by ZhorifCraft451** [comment]
maksudnya?
