### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ZhorifCraft451** [DavyCraft648/MCFurniture#9]
![WhatsApp Image 2023-07-10 at 18 11 24](https://github.com/DavyCraft648/MCFurniture/assets/75656616/49e70b4c-236a-4177-a657-a3a777a8ae00)

this is what happen if we break a furniture

**Comment by Azvyl** [comment]
the file cannot be accessed

**Comment by ZhorifCraft451** [comment]
umm sorry, wait i will show the picture

**Comment by ZhorifCraft451** [comment]
done, now the picture be accessed
